/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'categoryId' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'lastUpdatedDate' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Nat], [Category], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderCategories' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Category], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'categoryId' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'lastUpdatedDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Nat], [Category], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderCategories' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Category], []),
  });
};

export const init = ({ IDL }) => { return []; };