/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'categoryId' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'lastUpdatedDate' : IDL.Int,
});
export const Product = IDL.Record({
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'barcode' : IDL.Text,
  'lastUpdatedDate' : IDL.Int,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'price' : IDL.Opt(IDL.Float64),
});
export const ImportData = IDL.Record({
  'categories' : IDL.Vec(Category),
  'products' : IDL.Vec(Product),
});
export const ImportResult = IDL.Record({
  'importedCategoryCount' : IDL.Nat,
  'importedProductCount' : IDL.Nat,
  'errorMessages' : IDL.Vec(IDL.Text),
  'success' : IDL.Bool,
});
export const SaleItem = IDL.Record({
  'categoryId' : IDL.Nat,
  'categoryName' : IDL.Text,
  'saleId' : IDL.Nat,
  'endDate' : IDL.Int,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'barcode' : IDL.Text,
  'lastUpdatedDate' : IDL.Int,
  'salePrice' : IDL.Float64,
  'price' : IDL.Opt(IDL.Float64),
  'discountPercentage' : IDL.Float64,
  'productBarcode' : IDL.Text,
  'startDate' : IDL.Int,
});
export const ExportProduct = IDL.Record({
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'barcode' : IDL.Text,
  'lastUpdatedDate' : IDL.Int,
  'price' : IDL.Opt(IDL.Float64),
});
export const ExportPayload = IDL.Record({
  'categories' : IDL.Vec(Category),
  'itemCounts' : IDL.Record({ 'categories' : IDL.Nat, 'products' : IDL.Nat }),
  'products' : IDL.Vec(ExportProduct),
  'exportTimestamp' : IDL.Int,
});
export const StoreDetails = IDL.Record({
  'storeId' : IDL.Nat,
  'instagram' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'createdDate' : IDL.Int,
  'whatsapp' : IDL.Text,
  'storeHours' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'facebook' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'coordinates' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProductWithSale = IDL.Record({
  'isOnSale' : IDL.Bool,
  'salePrice' : IDL.Opt(IDL.Float64),
  'discountPercentage' : IDL.Opt(IDL.Float64),
  'product' : Product,
});
export const CategorizedProductWithSale = IDL.Record({
  'categoryId' : IDL.Nat,
  'totalProducts' : IDL.Nat,
  'categoryName' : IDL.Text,
  'products' : IDL.Vec(ProductWithSale),
});
export const HomepageCategoriesResult = IDL.Record({
  'categories' : IDL.Vec(CategorizedProductWithSale),
  'totalCategories' : IDL.Nat,
});
export const PaginatedResponse = IDL.Record({
  'totalCount' : IDL.Nat,
  'items' : IDL.Vec(Product),
});
export const SaleItemArray = IDL.Record({
  'totalCount' : IDL.Nat,
  'items' : IDL.Vec(SaleItem),
});
export const AppUser = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const HomepageSearchResult = IDL.Record({
  'categoryId' : IDL.Nat,
  'productImageUrl' : IDL.Opt(IDL.Text),
  'categoryName' : IDL.Text,
  'name' : IDL.Text,
  'salePercentage' : IDL.Opt(IDL.Float64),
  'barcode' : IDL.Text,
  'salePrice' : IDL.Opt(IDL.Float64),
  'price' : IDL.Opt(IDL.Float64),
  'saleIsActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchImportData' : IDL.Func([ImportData], [ImportResult], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Nat], [Category], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Vec(IDL.Nat8)),
      ],
      [Product],
      [],
    ),
  'createSaleItem' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Int, IDL.Int],
      [SaleItem],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSaleItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'demoteToUserForAdmin' : IDL.Func([IDL.Principal], [], []),
  'exportAllData' : IDL.Func([], [ExportPayload], []),
  'filterProductsForSales' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getActiveSales' : IDL.Func([], [IDL.Vec(SaleItem)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getBothStoreDetails' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, StoreDetails))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getCategoryProductCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getHomepageCategories' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [HomepageCategoriesResult],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductPhoto' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
  'getProductsPage' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat, IDL.Nat],
      [PaginatedResponse],
      ['query'],
    ),
  'getProductsPageFeaturedFirst' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat, IDL.Nat],
      [PaginatedResponse],
      ['query'],
    ),
  'getSaleItemsPage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [SaleItemArray],
      ['query'],
    ),
  'getStoreDetails' : IDL.Func([IDL.Nat], [StoreDetails], []),
  'getTotalProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listManagedUsersForAdmin' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'promoteToAdminForAdmin' : IDL.Func([IDL.Principal], [], []),
  'reorderCategories' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchHomepageProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HomepageSearchResult)],
      ['query'],
    ),
  'toggleProductInStock' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'toggleSaleItemActiveStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Category], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Vec(IDL.Nat8)),
      ],
      [Product],
      [],
    ),
  'updateSaleItem' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Int, IDL.Int],
      [SaleItem],
      [],
    ),
  'updateStoreDetails' : IDL.Func([IDL.Nat, StoreDetails], [], []),
  'uploadProductPhoto' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'categoryId' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'lastUpdatedDate' : IDL.Int,
  });
  const Product = IDL.Record({
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'barcode' : IDL.Text,
    'lastUpdatedDate' : IDL.Int,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'price' : IDL.Opt(IDL.Float64),
  });
  const ImportData = IDL.Record({
    'categories' : IDL.Vec(Category),
    'products' : IDL.Vec(Product),
  });
  const ImportResult = IDL.Record({
    'importedCategoryCount' : IDL.Nat,
    'importedProductCount' : IDL.Nat,
    'errorMessages' : IDL.Vec(IDL.Text),
    'success' : IDL.Bool,
  });
  const SaleItem = IDL.Record({
    'categoryId' : IDL.Nat,
    'categoryName' : IDL.Text,
    'saleId' : IDL.Nat,
    'endDate' : IDL.Int,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'barcode' : IDL.Text,
    'lastUpdatedDate' : IDL.Int,
    'salePrice' : IDL.Float64,
    'price' : IDL.Opt(IDL.Float64),
    'discountPercentage' : IDL.Float64,
    'productBarcode' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const ExportProduct = IDL.Record({
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'barcode' : IDL.Text,
    'lastUpdatedDate' : IDL.Int,
    'price' : IDL.Opt(IDL.Float64),
  });
  const ExportPayload = IDL.Record({
    'categories' : IDL.Vec(Category),
    'itemCounts' : IDL.Record({ 'categories' : IDL.Nat, 'products' : IDL.Nat }),
    'products' : IDL.Vec(ExportProduct),
    'exportTimestamp' : IDL.Int,
  });
  const StoreDetails = IDL.Record({
    'storeId' : IDL.Nat,
    'instagram' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'createdDate' : IDL.Int,
    'whatsapp' : IDL.Text,
    'storeHours' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'facebook' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'coordinates' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProductWithSale = IDL.Record({
    'isOnSale' : IDL.Bool,
    'salePrice' : IDL.Opt(IDL.Float64),
    'discountPercentage' : IDL.Opt(IDL.Float64),
    'product' : Product,
  });
  const CategorizedProductWithSale = IDL.Record({
    'categoryId' : IDL.Nat,
    'totalProducts' : IDL.Nat,
    'categoryName' : IDL.Text,
    'products' : IDL.Vec(ProductWithSale),
  });
  const HomepageCategoriesResult = IDL.Record({
    'categories' : IDL.Vec(CategorizedProductWithSale),
    'totalCategories' : IDL.Nat,
  });
  const PaginatedResponse = IDL.Record({
    'totalCount' : IDL.Nat,
    'items' : IDL.Vec(Product),
  });
  const SaleItemArray = IDL.Record({
    'totalCount' : IDL.Nat,
    'items' : IDL.Vec(SaleItem),
  });
  const AppUser = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const HomepageSearchResult = IDL.Record({
    'categoryId' : IDL.Nat,
    'productImageUrl' : IDL.Opt(IDL.Text),
    'categoryName' : IDL.Text,
    'name' : IDL.Text,
    'salePercentage' : IDL.Opt(IDL.Float64),
    'barcode' : IDL.Text,
    'salePrice' : IDL.Opt(IDL.Float64),
    'price' : IDL.Opt(IDL.Float64),
    'saleIsActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchImportData' : IDL.Func([ImportData], [ImportResult], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Nat], [Category], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Vec(IDL.Nat8)),
        ],
        [Product],
        [],
      ),
    'createSaleItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Int, IDL.Int],
        [SaleItem],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSaleItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'demoteToUserForAdmin' : IDL.Func([IDL.Principal], [], []),
    'exportAllData' : IDL.Func([], [ExportPayload], []),
    'filterProductsForSales' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getActiveSales' : IDL.Func([], [IDL.Vec(SaleItem)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getBothStoreDetails' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, StoreDetails))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getCategoryProductCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getHomepageCategories' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [HomepageCategoriesResult],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductPhoto' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
    'getProductsPage' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat, IDL.Nat],
        [PaginatedResponse],
        ['query'],
      ),
    'getProductsPageFeaturedFirst' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat, IDL.Nat],
        [PaginatedResponse],
        ['query'],
      ),
    'getSaleItemsPage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [SaleItemArray],
        ['query'],
      ),
    'getStoreDetails' : IDL.Func([IDL.Nat], [StoreDetails], []),
    'getTotalProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listManagedUsersForAdmin' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'promoteToAdminForAdmin' : IDL.Func([IDL.Principal], [], []),
    'reorderCategories' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchHomepageProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HomepageSearchResult)],
        ['query'],
      ),
    'toggleProductInStock' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'toggleSaleItemActiveStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Category], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Vec(IDL.Nat8)),
        ],
        [Product],
        [],
      ),
    'updateSaleItem' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Int, IDL.Int],
        [SaleItem],
        [],
      ),
    'updateStoreDetails' : IDL.Func([IDL.Nat, StoreDetails], [], []),
    'uploadProductPhoto' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };