/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser { 'principal' : Principal, 'role' : UserRole }
export interface CategorizedProductWithSale {
  'categoryId' : bigint,
  'totalProducts' : bigint,
  'categoryName' : string,
  'products' : Array<ProductWithSale>,
}
export interface Category {
  'categoryId' : bigint,
  'order' : bigint,
  'name' : string,
  'createdDate' : bigint,
  'lastUpdatedDate' : bigint,
}
export interface ExportPayload {
  'categories' : Array<Category>,
  'itemCounts' : { 'categories' : bigint, 'products' : bigint },
  'products' : Array<ExportProduct>,
  'exportTimestamp' : bigint,
}
export interface ExportProduct {
  'categoryId' : bigint,
  'inStock' : boolean,
  'name' : string,
  'createdDate' : bigint,
  'description' : [] | [string],
  'isFeatured' : boolean,
  'barcode' : string,
  'lastUpdatedDate' : bigint,
  'store1InStock' : boolean,
  'price' : [] | [number],
  'store2InStock' : boolean,
}
export interface HomepageCategoriesResult {
  'categories' : Array<CategorizedProductWithSale>,
  'totalCategories' : bigint,
}
export interface HomepageSearchResult {
  'categoryId' : bigint,
  'categoryName' : string,
  'name' : string,
  'salePercentage' : [] | [number],
  'barcode' : string,
  'salePrice' : [] | [number],
  'photo' : [] | [Uint8Array],
  'price' : [] | [number],
  'saleIsActive' : boolean,
}
export interface ImportData {
  'categories' : Array<Category>,
  'products' : Array<Product>,
}
export interface ImportResult {
  'importedCategoryCount' : bigint,
  'importedProductCount' : bigint,
  'errorMessages' : Array<string>,
  'success' : boolean,
}
export interface PaginatedResponse {
  'totalCount' : bigint,
  'items' : Array<ProductV2>,
}
export interface Product {
  'categoryId' : bigint,
  'inStock' : boolean,
  'name' : string,
  'createdDate' : bigint,
  'description' : [] | [string],
  'isFeatured' : boolean,
  'barcode' : string,
  'lastUpdatedDate' : bigint,
  'store1InStock' : boolean,
  'photo' : [] | [Uint8Array],
  'price' : [] | [number],
  'store2InStock' : boolean,
}
export interface ProductV2 {
  'categoryId' : bigint,
  'categoryName' : string,
  'inStock' : boolean,
  'name' : string,
  'createdDate' : bigint,
  'description' : [] | [string],
  'isFeatured' : boolean,
  'barcode' : string,
  'lastUpdatedDate' : bigint,
  'store1InStock' : boolean,
  'photo' : [] | [Uint8Array],
  'price' : [] | [number],
  'store2InStock' : boolean,
}
export interface ProductWithSale {
  'isOnSale' : boolean,
  'salePrice' : [] | [number],
  'discountPercentage' : [] | [number],
  'product' : Product,
}
export interface SaleItem {
  'categoryId' : bigint,
  'categoryName' : string,
  'saleId' : bigint,
  'endDate' : bigint,
  'name' : string,
  'createdDate' : bigint,
  'description' : [] | [string],
  'isActive' : boolean,
  'barcode' : string,
  'lastUpdatedDate' : bigint,
  'salePrice' : number,
  'price' : [] | [number],
  'discountPercentage' : number,
  'productBarcode' : string,
  'startDate' : bigint,
}
export interface SaleItemArray {
  'totalCount' : bigint,
  'items' : Array<SaleItem>,
}
export interface StoreDetails {
  'storeId' : bigint,
  'instagram' : [] | [string],
  'name' : string,
  'lastUpdated' : bigint,
  'createdDate' : bigint,
  'whatsapp' : string,
  'storeHours' : Array<[string, string]>,
  'isActive' : boolean,
  'email' : string,
  'website' : [] | [string],
  'facebook' : [] | [string],
  'address' : string,
  'phone' : string,
  'coordinates' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchImportData' : ActorMethod<[ImportData], ImportResult>,
  'createCategory' : ActorMethod<[string, bigint], Category>,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      [] | [string],
      [] | [number],
      boolean,
      boolean,
      [] | [Uint8Array],
      boolean,
      boolean,
    ],
    Product
  >,
  'createSaleItem' : ActorMethod<[string, number, bigint, bigint], SaleItem>,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[string, string], undefined>,
  'deleteSaleItem' : ActorMethod<[bigint], boolean>,
  'demoteToUserForAdmin' : ActorMethod<[Principal], undefined>,
  'exportAllData' : ActorMethod<[], ExportPayload>,
  'filterProductsForSales' : ActorMethod<[string], Array<Product>>,
  'getActiveSales' : ActorMethod<[], Array<SaleItem>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getBothStoreDetails' : ActorMethod<[], Array<[bigint, StoreDetails]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryById' : ActorMethod<[bigint], [] | [Category]>,
  'getCategoryProductCounts' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getHomepageCategories' : ActorMethod<
    [bigint, bigint],
    HomepageCategoriesResult
  >,
  'getProduct' : ActorMethod<[string], ProductWithSale>,
  'getProductPhoto' : ActorMethod<[string], Uint8Array>,
  'getProductsPage' : ActorMethod<
    [string, [] | [bigint], bigint, bigint],
    PaginatedResponse
  >,
  'getProductsPageFeaturedFirst' : ActorMethod<
    [string, [] | [bigint], bigint, bigint],
    { 'totalCount' : bigint, 'items' : Array<ProductWithSale> }
  >,
  'getSaleItemsPage' : ActorMethod<
    [string, bigint, bigint, boolean],
    SaleItemArray
  >,
  'getStoreDetails' : ActorMethod<[bigint], StoreDetails>,
  'getTotalProductCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listManagedUsersForAdmin' : ActorMethod<[], Array<AppUser>>,
  'promoteToAdminForAdmin' : ActorMethod<[Principal], undefined>,
  'reorderCategories' : ActorMethod<[Array<[bigint, bigint]>], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchHomepageProducts' : ActorMethod<[string], Array<HomepageSearchResult>>,
  'toggleProductInStock' : ActorMethod<[string], boolean>,
  'toggleSaleItemActiveStatus' : ActorMethod<[bigint], boolean>,
  'updateCategory' : ActorMethod<[bigint, string, bigint], Category>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      [] | [string],
      [] | [number],
      boolean,
      boolean,
      [] | [Uint8Array],
      boolean,
      boolean,
    ],
    Product
  >,
  'updateSaleItem' : ActorMethod<[bigint, number, bigint, bigint], SaleItem>,
  'updateStoreDetails' : ActorMethod<[bigint, StoreDetails], undefined>,
  'uploadProductPhoto' : ActorMethod<[string, Uint8Array], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];